keys:
  - &connor age1hwl73jx8xmvuy2pwn9cxvcqad3msgpzvpl9w046vc0t8xcz9ks3qx74kpq
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
      - age:
          - *connor
  - path_regex: hosts/effigy/[^/]+\.(yaml)$
    key_groups:
      - age:
          - *connor
  - path_regex: hosts/opus/.+\.(yaml)$
    key_groups:
      - age:
          - *connor
